//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLastPart
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbExamStudentEntities : DbContext
    {
        public DbExamStudentEntities()
            : base("name=DbExamStudentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLUB> CLUBS { get; set; }
        public virtual DbSet<Lecture> Lectures { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Product> Products { get; set; }
    
        public virtual ObjectResult<ClubList_Result> ClubList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ClubList_Result>("ClubList");
        }
    }
}
