//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLastPart
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int NoteID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> Lecture { get; set; }
        public Nullable<short> Exam1 { get; set; }
        public Nullable<short> Exam2 { get; set; }
        public Nullable<short> Exam3 { get; set; }
        public Nullable<decimal> Average { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Lecture Lecture1 { get; set; }
        public virtual Student Student { get; set; }
    }
}
